In [11]:
import cv2
import os
import numpy as np

directory_path = 'MCI/video_sequence'
frame_list = []

width = height = 512

for filename in os.listdir(directory_path):
    if filename.endswith(".avi"):
        video_path = os.path.join(directory_path, filename)
        cap = cv2.VideoCapture(video_path)

        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break

            # Convert frame to grayscale
            gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

            # Resize the frame
            resized_frame = cv2.resize(gray_frame, (width, height))

            # Add the frame to the list
            frame_list.append(resized_frame)

        cap.release()


70030_R_1_1_2020_0_0_0_V011.avi
70031_R_1_1_2020_0_0_0_V008.avi
70031_R_1_1_2020_0_0_0_V009.avi
70030_L_1_1_2020_0_0_0_V006.avi
70030_R_1_1_2020_0_0_0_V010.avi
70030_R_1_1_2020_0_0_0_V012.avi
70030_L_1_1_2020_0_0_0_V004.avi
70030_L_1_1_2020_0_0_0_V005.avi
70030_R_1_1_2020_0_0_0_V007.avi
70030_L_1_1_2020_0_0_0_V001.avi
70030_L_1_1_2020_0_0_0_V002.avi
70030_L_1_1_2020_0_0_0_V003.avi
60002_R_1_10_2020_9_21_21_V001.avi
70027_L_1_1_2020_0_0_0_V005.avi
70027_R_1_1_2020_0_0_0_V007.avi
60008_R_1_31_2020_15_31_3_V006.avi
60008_R_1_31_2020_15_31_3_V007.avi
70027_R_1_1_2020_0_0_0_V012.avi
70027_L_1_1_2020_0_0_0_V004.avi
70028_L_1_1_2020_0_0_0_V001.avi
70028_L_1_1_2020_0_0_0_V003.avi
60002_R_1_10_2020_9_21_21_V002.avi
70027_L_1_1_2020_0_0_0_V006.avi
70027_R_1_1_2020_0_0_0_V010.avi
60008_R_1_31_2020_15_31_3_V005.avi
60008_R_1_31_2020_15_31_3_V004.avi
60008_R_1_31_2020_15_31_3_V010.avi
70027_R_1_1_2020_0_0_0_V011.avi
60002_R_1_10_2020_9_21_21_V003.avi
70028_L_1_1_2020_0_0_0_V002.avi
70028_R_1_1_2020

In [9]:
frame_list = frame_list[330:660]

In [10]:
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display

def show_frame(frame_index):
    plt.imshow(frame_list[frame_index], cmap='gray')
    plt.axis('off')
    plt.show()

# Create a slider to browse through the frames
frame_slider = widgets.IntSlider(value=0, min=0, max=len(frame_list)-1, step=1, description='Frame:')

# Display the widget
widgets.interactive(show_frame, frame_index=frame_slider)


interactive(children=(IntSlider(value=0, description='Frame:', max=329), Output()), _dom_classes=('widget-inte…

In [5]:
print(frame_list[0])  # Check the first frame
print(frame_list[0].max(), frame_list[0].min())  # Check the range of pixel values


[[73 74 71 ... 41  6  4]
 [77 70 70 ... 37  7  3]
 [83 76 81 ... 31 10 10]
 ...
 [79 80 76 ... 37  6  3]
 [86 75 92 ... 56  5  5]
 [80 81 66 ... 51  6  3]]
147 0
